spring.application.name=budgeting

spring.config.import=optional:file:.env[.properties]

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.response-format.type=TEXT

spring.ai.openai.audio.transcription.options.model=whisper-1
spring.ai.openai.audio.transcription.options.language=pt
spring.ai.openai.audio.transcription.options.temperature=0
spring.ai.openai.audio.transcription.options.response-fornat=TEXT
spring.ai.openai.audio.transcription.options.prompt= Áudio em portugues brasileiro. Audio comtem gastos financeiros

spring.ai.model.audio.speech=openai
spring.ai.model.audio.speech.options.model=gpt-4o-mini-tts
spring.ai.model.audio.speech.options.voice=nova
spring.ai.model.audio.speech.options.speed=1.2
spring.ai.model.audio.speech.options.resposne-format=mp3

loggin.level.org.springframework.ai=DEBUG